blank_issues_enabled: false
contact_links:
  - name: Usage Questions
    url: https://github.com/sqlalchemy/sqlalchemy/discussions/new?category=Usage-Questions
    about: Questions and Answers for SQLAlchemy Users 
  - name: Ideas / Feature Proposals
    url: https://github.com/sqlalchemy/sqlalchemy/discussions/new?category=Ideas
    about: Use this for initial discussion for new features and suggestions
